"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertTriangle,
  Search,
  Settings,
  Activity,
  BarChart3,
  Network,
  CheckCircle,
  Rocket,
  BookOpen,
  Clock,
  ShieldCheck,
  XCircle,
  Loader2,
} from "lucide-react";
import type { SREEvent } from "@/lib/sre-events";

import { SparklineChart, AreaChart, BarChart } from "../components/artifacts/metric-charts";
import { TopologyDiagram, DependencyGraph } from "../components/artifacts/architecture-diagrams";
import { StatusGrid, DiffView, LogTrace } from "../components/artifacts/detail-artifacts";

// ── Issue status ─────────────────────────────────────────────────────────────

type IssueStatus = "pending" | "approved" | "applying" | "resolved" | "rejected";

const STATUS_CONFIG: Record<IssueStatus, { label: string; color: string; bg: string; icon: React.ElementType }> = {
  pending: { label: "Awaiting Approval", color: "text-amber-600 dark:text-amber-400", bg: "bg-amber-50 dark:bg-amber-950/30", icon: Clock },
  approved: { label: "Approved", color: "text-blue-600 dark:text-blue-400", bg: "bg-blue-50 dark:bg-blue-950/30", icon: ShieldCheck },
  applying: { label: "Applying Fix…", color: "text-blue-600 dark:text-blue-400", bg: "bg-blue-50 dark:bg-blue-950/30", icon: Loader2 },
  resolved: { label: "Applied", color: "text-emerald-600 dark:text-emerald-400", bg: "bg-emerald-50 dark:bg-emerald-950/30", icon: CheckCircle },
  rejected: { label: "Rejected", color: "text-neutral-500 dark:text-neutral-400", bg: "bg-neutral-50 dark:bg-neutral-800/30", icon: XCircle },
};

// ── Proposed fix types ───────────────────────────────────────────────────────

interface DiffLine {
  type: "added" | "removed" | "context";
  content: string;
}

interface ProposedFix {
  action: string;
  description: string;
  file?: string;
  diff?: DiffLine[];
}

// ── Per-event fix overrides (keyed by event ID) ──────────────────────────────

const EVENT_FIXES: Record<string, ProposedFix> = {
  "evt-001": {
    action: "Enforce strict rate limiting for abusive IP range",
    description: "The agent identified a DDoS pattern from 198.51.100.0/24 generating 12,400 req/s against /api/checkout. The proposed fix adds an aggressive rate limit rule that caps this CIDR block to 10 req/s with automatic 30-minute bans on violation, while preserving normal traffic flow for all other clients.",
    file: "api-gateway/config/rate-limiter.yaml",
    diff: [
      { type: "context", content: "# rate-limiter.yaml" },
      { type: "context", content: "rules:" },
      { type: "context", content: "  - path: /api/checkout" },
      { type: "context", content: "    limit: 500" },
      { type: "context", content: "    window: 1s" },
      { type: "context", content: "    action: reject" },
      { type: "context", content: "" },
      { type: "added", content: "  # DDoS mitigation — auto-generated by agent" },
      { type: "added", content: "  - path: /api/checkout" },
      { type: "added", content: "    match:" },
      { type: "added", content: "      source_cidr: 198.51.100.0/24" },
      { type: "added", content: "    limit: 10" },
      { type: "added", content: "    window: 1s" },
      { type: "added", content: "    action: reject" },
      { type: "added", content: "    ban_duration: 30m" },
      { type: "added", content: "    log: true" },
      { type: "added", content: "" },
      { type: "context", content: "  - path: /api/search" },
      { type: "context", content: "    limit: 500" },
      { type: "context", content: "    window: 1s" },
    ],
  },
};

// ── Default fixes per event type (fallback) ──────────────────────────────────

const DEFAULT_FIXES: Record<string, ProposedFix> = {
  incident_detected: {
    action: "Enable circuit breaker & scale up replicas",
    description: "The agent will enable the circuit breaker on the affected service to stop cascading failures, then scale the deployment from 3 to 5 replicas to absorb the error backlog.",
  },
  root_cause_found: {
    action: "Reduce timeout & enable retry with backoff",
    description: "The agent will update the upstream adapter timeout from 30s to 5s and enable exponential retry with a maximum of 3 attempts to prevent connection pool exhaustion.",
  },
  config_change: {
    action: "Apply recommended config patch",
    description: "The agent will apply the configuration diff shown above to production. The change has been validated against the canary environment with zero errors over a 15-minute window.",
  },
  instrumentation_update: {
    action: "Deploy updated probe to all replicas",
    description: "The agent will compile the eBPF probe for the target kernel version and deploy it across all replicas. Histogram collection will be verified post-deployment.",
  },
  metric_anomaly: {
    action: "Auto-scale & trigger resource profiling",
    description: "The agent will initiate horizontal auto-scaling based on current load, and attach a resource profiler to identify the root cause of the anomaly.",
  },
  service_topology_change: {
    action: "Update service mesh routing rules",
    description: "The agent will update the Envoy sidecar configuration to reflect the new topology and ensure traffic is routed correctly to healthy endpoints.",
  },
  alert_resolved: {
    action: "Close incident & update post-mortem",
    description: "The agent will mark the incident as resolved in the incident management system, close the PagerDuty alert, and generate a post-mortem draft.",
  },
  deployment_detected: {
    action: "Promote canary to stable",
    description: "The agent will shift 100% of traffic to the new version after confirming error rate and latency are within SLO thresholds during the canary window.",
  },
  runbook_executed: {
    action: "Execute automated remediation runbook",
    description: "The agent will run the associated runbook steps sequentially with rollback checkpoints. Each step will be verified before proceeding to the next.",
  },
};

function getProposedFix(event: SREEvent): ProposedFix {
  return EVENT_FIXES[event.id] ?? DEFAULT_FIXES[event.eventType] ?? DEFAULT_FIXES.incident_detected;
}

// ── Default initial statuses (mock: recent critical/warning = pending, old ones = resolved) ──

function getInitialStatus(event: SREEvent): IssueStatus {
  if (event.id === "evt-001") return "pending";
  return "resolved";
}

// ── Severity colors ──────────────────────────────────────────────────────────

const SEVERITY_COLORS: Record<string, string> = {
  critical: "#ef4444",
  warning: "#f59e0b",
  info: "#3b82f6",
  success: "#22c55e",
};

const SEVERITY_BG: Record<string, string> = {
  critical: "bg-red-50 dark:bg-red-950/20",
  warning: "bg-amber-50 dark:bg-amber-950/20",
  info: "bg-blue-50 dark:bg-blue-950/20",
  success: "bg-emerald-50 dark:bg-emerald-950/20",
};

// ── Event type icons & labels ────────────────────────────────────────────────

const EVENT_TYPE_CONFIG: Record<string, { icon: React.ElementType; label: string }> = {
  incident_detected: { icon: AlertTriangle, label: "Incident" },
  root_cause_found: { icon: Search, label: "Root Cause" },
  config_change: { icon: Settings, label: "Config" },
  instrumentation_update: { icon: Activity, label: "Instrumentation" },
  metric_anomaly: { icon: BarChart3, label: "Anomaly" },
  service_topology_change: { icon: Network, label: "Topology" },
  alert_resolved: { icon: CheckCircle, label: "Resolved" },
  deployment_detected: { icon: Rocket, label: "Deploy" },
  runbook_executed: { icon: BookOpen, label: "Runbook" },
};

// ── Relative time ────────────────────────────────────────────────────────────

function relativeTime(timestamp: string): string {
  const now = Date.now();
  const then = new Date(timestamp).getTime();
  const diffMs = now - then;
  const diffMin = Math.floor(diffMs / 60000);
  if (diffMin < 1) return "just now";
  if (diffMin < 60) return `${diffMin}m ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  const diffDay = Math.floor(diffHr / 24);
  return `${diffDay}d ago`;
}

// ── Artifact Renderer ────────────────────────────────────────────────────────

function ArtifactRenderer({ event }: { event: SREEvent }) {
  switch (event.artifactType) {
    case "sparkline":
      return <SparklineChart data={event.artifactData} />;
    case "area_chart":
      return <AreaChart data={event.artifactData} />;
    case "bar_chart":
      return <BarChart data={event.artifactData} />;
    case "topology_diagram":
      return <TopologyDiagram {...event.artifactData} />;
    case "dependency_graph":
      return <DependencyGraph {...event.artifactData} />;
    case "status_grid":
      return <StatusGrid {...event.artifactData} />;
    case "diff_view":
      return <DiffView {...event.artifactData} />;
    case "log_trace":
      return <LogTrace {...event.artifactData} />;
    case "timeline":
      return (
        <svg viewBox="0 0 768 300" className="w-full h-full" role="img" aria-label="Event timeline">
          <line x1={60} y1={20} x2={60} y2={280} stroke="currentColor" className="text-neutral-300 dark:text-neutral-600" strokeWidth={2} />
          {event.artifactData.events.map((evt, i) => {
            const y = 30 + (i / Math.max(event.artifactData.events.length - 1, 1)) * 240;
            return (
              <g key={i}>
                <circle cx={60} cy={y} r={5} className="fill-blue-500 dark:fill-blue-400" />
                <text x={80} y={y - 4} fontSize={10} className="fill-neutral-500 dark:fill-neutral-400" fontFamily="ui-monospace, monospace">
                  {evt.time}
                </text>
                <text x={80} y={y + 10} fontSize={11} fill="currentColor" className="text-neutral-700 dark:text-neutral-300">
                  {evt.label}
                </text>
              </g>
            );
          })}
        </svg>
      );
    default:
      return null;
  }
}

// ── Status Badge (inline) ────────────────────────────────────────────────────

function StatusBadge({ status }: { status: IssueStatus }) {
  const config = STATUS_CONFIG[status];
  const Icon = config.icon;
  const isSpinning = status === "applying";

  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium ${config.color} ${config.bg}`}>
      <Icon size={12} className={isSpinning ? "animate-spin" : ""} />
      {config.label}
    </span>
  );
}

// ── Event Row ────────────────────────────────────────────────────────────────

interface EventRowProps {
  event: SREEvent;
  index: number;
  status: IssueStatus;
  onSelect: () => void;
}

function EventRow({ event, index, status, onSelect }: EventRowProps) {
  const severityColor = SEVERITY_COLORS[event.severity] ?? SEVERITY_COLORS.info;
  const config = EVENT_TYPE_CONFIG[event.eventType] ?? EVENT_TYPE_CONFIG.incident_detected;
  const Icon = config.icon;
  const isActionable = status === "pending";

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay: index * 0.03 }}
    >
      <button
        onClick={onSelect}
        className="group w-full text-left"
      >
        <div className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-colors hover:bg-neutral-50 dark:hover:bg-neutral-800/50 ${isActionable ? "bg-amber-50/40 dark:bg-amber-950/10" : ""}`}>
          {/* Severity dot */}
          <span
            className="w-2 h-2 rounded-full shrink-0"
            style={{ backgroundColor: severityColor }}
          />

          {/* Icon */}
          <Icon
            size={16}
            className="shrink-0 text-neutral-400 dark:text-neutral-500"
          />

          {/* Title */}
          <span className="flex-1 text-sm font-medium text-neutral-900 dark:text-neutral-100 truncate">
            {event.title}
          </span>

          {/* Status badge */}
          <span className="hidden sm:inline-flex shrink-0">
            <StatusBadge status={status} />
          </span>

          {/* Service */}
          <span className="hidden md:inline-block shrink-0 px-2 py-0.5 rounded bg-neutral-100 dark:bg-neutral-800 text-xs font-mono text-neutral-500 dark:text-neutral-400">
            {event.service}
          </span>

          {/* Time */}
          <span className="shrink-0 w-16 text-right text-xs text-neutral-400 dark:text-neutral-500">
            {relativeTime(event.timestamp)}
          </span>
        </div>
      </button>
    </motion.div>
  );
}

// ── Detail Modal ─────────────────────────────────────────────────────────────

interface DetailModalProps {
  event: SREEvent;
  status: IssueStatus;
  onClose: () => void;
  onApprove: () => void;
  onReject: () => void;
}

function DetailModal({ event, status, onClose, onApprove, onReject }: DetailModalProps) {
  const panelRef = useRef<HTMLDivElement>(null);
  const severityColor = SEVERITY_COLORS[event.severity] ?? SEVERITY_COLORS.info;
  const config = EVENT_TYPE_CONFIG[event.eventType] ?? EVENT_TYPE_CONFIG.incident_detected;
  const Icon = config.icon;
  const fix = getProposedFix(event);

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onClose]);

  const handleBackdropClick = useCallback(
    (e: React.MouseEvent) => {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        onClose();
      }
    },
    [onClose]
  );

  return (
    <motion.div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.2 }}
      onClick={handleBackdropClick}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/40 dark:bg-black/60" />

      {/* Panel */}
      <motion.div
        ref={panelRef}
        className="relative w-full max-w-3xl max-h-[85vh] overflow-y-auto rounded-xl bg-white dark:bg-neutral-900 shadow-2xl"
        initial={{ y: 40, opacity: 0, scale: 0.97 }}
        animate={{ y: 0, opacity: 1, scale: 1 }}
        exit={{ y: 40, opacity: 0, scale: 0.97 }}
        transition={{ type: "spring", stiffness: 400, damping: 30 }}
      >
        {/* Content */}
        <div className="p-6 space-y-5">
          {/* Badges row */}
          <div className="flex items-center gap-2 flex-wrap">
            <span
              className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium text-white"
              style={{ backgroundColor: severityColor }}
            >
              <Icon size={12} />
              {config.label}
            </span>
            <span className="px-2 py-0.5 rounded bg-neutral-100 dark:bg-neutral-800 text-xs font-mono text-neutral-600 dark:text-neutral-400">
              {event.service}
            </span>
            <StatusBadge status={status} />
            <span className="text-xs text-neutral-400 dark:text-neutral-500 ml-auto">
              {relativeTime(event.timestamp)}
            </span>
          </div>

          {/* Title + summary */}
          <div>
            <h2 className="text-xl font-semibold text-neutral-900 dark:text-neutral-100">
              {event.title}
            </h2>
            <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400 leading-relaxed">
              {event.summary}
            </p>
          </div>

          {/* Proposed fix */}
          <div className="rounded-lg border border-neutral-200 dark:border-neutral-700/60 overflow-hidden">
            <div className="px-4 py-2.5 bg-neutral-50 dark:bg-neutral-800/50 border-b border-neutral-200 dark:border-neutral-700/60">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
                Proposed Fix
              </h3>
            </div>
            <div className="px-4 py-3 space-y-3">
              <p className="text-sm font-medium text-neutral-900 dark:text-neutral-100">
                {fix.action}
              </p>
              <p className="text-sm text-neutral-500 dark:text-neutral-400 leading-relaxed">
                {fix.description}
              </p>

              {/* Code diff */}
              {fix.diff && (
                <div className="rounded-lg border border-neutral-200 dark:border-neutral-700/50 overflow-hidden">
                  {fix.file && (
                    <div className="px-3 py-1.5 bg-neutral-100 dark:bg-neutral-800 border-b border-neutral-200 dark:border-neutral-700/50">
                      <span className="text-xs font-mono text-neutral-500 dark:text-neutral-400">
                        {fix.file}
                      </span>
                    </div>
                  )}
                  <div className="overflow-x-auto">
                    <pre className="text-[13px] leading-6 font-mono">
                      {fix.diff.map((line, i) => (
                        <div
                          key={i}
                          className={
                            line.type === "added"
                              ? "bg-emerald-50 dark:bg-emerald-950/30 text-emerald-800 dark:text-emerald-300"
                              : line.type === "removed"
                                ? "bg-red-50 dark:bg-red-950/30 text-red-800 dark:text-red-300"
                                : "text-neutral-600 dark:text-neutral-400"
                          }
                        >
                          <span className="inline-block w-6 text-center text-neutral-400 dark:text-neutral-600 select-none shrink-0">
                            {line.type === "added" ? "+" : line.type === "removed" ? "−" : " "}
                          </span>
                          <span className="px-2">{line.content}</span>
                        </div>
                      ))}
                    </pre>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Action buttons */}
          {status === "pending" && (
            <div className="flex items-center gap-3 pt-1">
              <button
                onClick={onApprove}
                className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium transition-colors"
              >
                <ShieldCheck size={16} />
                Approve & Apply
              </button>
              <button
                onClick={onReject}
                className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg bg-neutral-100 dark:bg-neutral-800 hover:bg-neutral-200 dark:hover:bg-neutral-700 text-neutral-700 dark:text-neutral-300 text-sm font-medium transition-colors"
              >
                <XCircle size={16} />
                Reject
              </button>
            </div>
          )}

          {status === "applying" && (
            <div className="flex items-center gap-2 pt-1 text-sm text-blue-600 dark:text-blue-400">
              <Loader2 size={16} className="animate-spin" />
              Agent is applying the fix…
            </div>
          )}

          {status === "approved" && (
            <div className="flex items-center gap-2 pt-1 text-sm text-blue-600 dark:text-blue-400">
              <ShieldCheck size={16} />
              Fix approved, queued for execution.
            </div>
          )}

          {status === "resolved" && (
            <div className="flex items-center gap-2 pt-1 text-sm text-emerald-600 dark:text-emerald-400">
              <CheckCircle size={16} />
              Fix has been applied.
            </div>
          )}

          {status === "rejected" && (
            <div className="flex items-center gap-2 pt-1 text-sm text-neutral-500 dark:text-neutral-400">
              <XCircle size={16} />
              Fix was rejected. No changes applied.
            </div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ── Event List ───────────────────────────────────────────────────────────────

interface EventListProps {
  events: SREEvent[];
}

export function EventList({ events }: EventListProps) {
  const [selectedEvent, setSelectedEvent] = useState<SREEvent | null>(null);
  const [statuses, setStatuses] = useState<Record<string, IssueStatus>>(() => {
    const initial: Record<string, IssueStatus> = {};
    for (const event of events) {
      initial[event.id] = getInitialStatus(event);
    }
    return initial;
  });

  const handleApprove = useCallback((eventId: string) => {
    setStatuses((prev) => ({ ...prev, [eventId]: "approved" }));

    // Simulate: approved -> applying after 500ms -> resolved after 3s
    setTimeout(() => {
      setStatuses((prev) => ({ ...prev, [eventId]: "applying" }));
    }, 500);
    setTimeout(() => {
      setStatuses((prev) => ({ ...prev, [eventId]: "resolved" }));
    }, 3500);
  }, []);

  const handleReject = useCallback((eventId: string) => {
    setStatuses((prev) => ({ ...prev, [eventId]: "rejected" }));
  }, []);

  if (events.length === 0) {
    return (
      <div className="flex items-center justify-center h-[60vh]">
        <p className="text-neutral-500">No events recorded.</p>
      </div>
    );
  }

  return (
    <>
      <div className="max-w-4xl mx-auto px-2 py-4">
        {/* Column headers */}
        <div className="flex items-center gap-3 px-4 pb-2 text-[11px] font-medium uppercase tracking-wider text-neutral-400 dark:text-neutral-500 select-none">
          <span className="w-2 shrink-0" />
          <span className="w-4 shrink-0" />
          <span className="flex-1">Issue</span>
          <span className="hidden sm:inline-block shrink-0 w-32 text-center">Status</span>
          <span className="hidden md:inline-block shrink-0 w-28 text-center">Service</span>
          <span className="shrink-0 w-16 text-right">When</span>
        </div>

        <div className="border-t border-neutral-100 dark:border-neutral-800" />

        {/* Event rows */}
        <div className="divide-y divide-neutral-100 dark:divide-neutral-800/50">
          {events.map((event, index) => (
            <EventRow
              key={event.id}
              event={event}
              index={index}
              status={statuses[event.id]}
              onSelect={() => setSelectedEvent(event)}
            />
          ))}
        </div>
      </div>

      {/* Modal */}
      <AnimatePresence>
        {selectedEvent && (
          <DetailModal
            event={selectedEvent}
            status={statuses[selectedEvent.id]}
            onClose={() => setSelectedEvent(null)}
            onApprove={() => handleApprove(selectedEvent.id)}
            onReject={() => handleReject(selectedEvent.id)}
          />
        )}
      </AnimatePresence>
    </>
  );
}
